# Generated by Django 4.0.4 on 2022-05-13 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Travel_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.TextField(blank=True, max_length=1024, null=True)),
                ('script', models.TextField(blank=True, max_length=1024, null=True)),
                ('place_name', models.TextField(blank=True, max_length=16, null=True)),
                ('traffic', models.TextField(blank=True, max_length=1024, null=True)),
                ('accomdation', models.TextField(blank=True, max_length=8192, null=True)),
                ('addr_accomdation', models.TextField(blank=True, max_length=2048, null=True)),
                ('food', models.TextField(blank=True, max_length=1024, null=True)),
                ('activity', models.TextField(blank=True, max_length=1024, null=True)),
                ('sightseeing', models.TextField(blank=True, max_length=8192, null=True)),
                ('image_head', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_1', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_2', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_3', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_accomdation', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_food', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_activity', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_sightseeing', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('travel_box_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GetPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_box_id', models.CharField(max_length=32)),
                ('user_image_1', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('user_image_2', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('user_image_3', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('box_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelbox.travel_box')),
            ],
        ),
    ]
