# Generated by Django 4.0.4 on 2022-05-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0002_alter_travel_box_travel_box_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_box',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='image_accomdation',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='image_activity',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='image_food',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='image_head',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='image_sightseeing',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
    ]
