# Generated by Django 4.0.4 on 2022-05-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0003_alter_travel_box_image_1_alter_travel_box_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_box',
            name='travel_box_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
