# Generated by Django 4.0.4 on 2022-05-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0004_travel_box_travel_box_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_box',
            name='travel_box_id',
        ),
    ]
