# Generated by Django 4.0.4 on 2022-05-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0006_travel_box_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpic',
            name='checked',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
