# Generated by Django 4.0.4 on 2022-05-17 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelbox', '0007_getpic_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpic',
            name='getpic_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
