# Generated by Django 4.0.4 on 2022-05-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0009_remove_getpic_getpic_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel_box',
            old_name='accomdation',
            new_name='accomdation_1',
        ),
        migrations.RenameField(
            model_name='travel_box',
            old_name='sightseeing',
            new_name='accomdation_2',
        ),
        migrations.RenameField(
            model_name='travel_box',
            old_name='activity',
            new_name='activity_1',
        ),
        migrations.RenameField(
            model_name='travel_box',
            old_name='food',
            new_name='activity_2',
        ),
        migrations.RenameField(
            model_name='travel_box',
            old_name='addr_accomdation',
            new_name='addr_accomdation_1',
        ),
        migrations.RenameField(
            model_name='travel_box',
            old_name='image_accomdation',
            new_name='image_accomdation_1',
        ),
        migrations.RenameField(
            model_name='travel_box',
            old_name='image_activity',
            new_name='image_accomdation_2',
        ),
        migrations.RenameField(
            model_name='travel_box',
            old_name='image_food',
            new_name='image_accomdation_3',
        ),
        migrations.RenameField(
            model_name='travel_box',
            old_name='image_sightseeing',
            new_name='image_activity_1',
        ),
        migrations.AddField(
            model_name='travel_box',
            name='accomdation_3',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='activity_3',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='addr_accomdation_2',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='addr_accomdation_3',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='addr_activity_1',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='addr_activity_2',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='addr_activity_3',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='addr_food_1',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='addr_food_2',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='addr_food_3',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='addr_sightseeing_1',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='addr_sightseeing_2',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='addr_sightseeing_3',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='food_1',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='food_2',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='food_3',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_activity_2',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_activity_3',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_food_1',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_food_2',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_food_3',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_sightseeing_1',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_sightseeing_2',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_sightseeing_3',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='sightseeing_1',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='sightseeing_2',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='sightseeing_3',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
    ]
