# Generated by Django 4.0.4 on 2022-05-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alien_type',
            field=models.ImageField(upload_to='static/alien/%y'),
        ),
    ]
