# Generated by Django 4.0.4 on 2022-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_alter_profile_alien_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alien_name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
