# Generated by Django 4.0.4 on 2022-05-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_profile_alien_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select',
            name='selection_state',
            field=models.CharField(choices=[('preparing', '여행 준비 중'), ('prepared', '여행 준비 끝'), ('on_travel', '여행 중'), ('finished', '여행 완료')], default='preparing', max_length=32),
        ),
    ]
