# Generated by Django 4.0.4 on 2022-05-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poten_user_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
