# Generated by Django 4.0.4 on 2022-05-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_uid', models.CharField(max_length=64)),
                ('question1', models.CharField(max_length=32)),
                ('question2', models.CharField(max_length=32)),
                ('question3', models.CharField(max_length=32)),
                ('question4', models.CharField(max_length=32)),
                ('question5', models.CharField(max_length=32)),
                ('question6', models.CharField(max_length=32)),
                ('question7', models.CharField(max_length=32)),
                ('question8', models.CharField(max_length=32)),
                ('question9', models.CharField(max_length=32)),
            ],
        ),
    ]
