# Generated by Django 4.0.4 on 2022-05-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_surveyquestion_question1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='question_start',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
