# Generated by Django 4.0.4 on 2022-05-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_surveyquestion_question_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='question_start',
            new_name='question0',
        ),
    ]
