# Generated by Django 4.0.4 on 2022-05-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_rename_question_start_surveyquestion_question0'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='question10',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
